### PR TITLE
chore: update `@google-cloud/common` to `0.20.0`

### PR DESCRIPTION
**Pull request by DominicKramer**

### CODE REVIEW

**Comment by DominicKramer** [comment]
PTAL

**Comment by DominicKramer** [comment]
@kjin That is the type that matched the logger used in the error reporting library.  I was expecting to be able to use a `Logger`, but it seems like a `CustomLevelsLogger` is not a `Logger`.

**Comment by DominicKramer** [comment]
@kjin This is ready for another look.

**Comment by JustinBeckwith** [comment]
@DominicKramer this PR needs a little update love, then it should be good to go :)

**Pull request merged**
