### PR TITLE
chore: merge the old and new README files

### PR DESCRIPTION
**Pull request by DominicKramer**

### CODE REVIEW

**Comment by DominicKramer** [comment]
PTAL.  It might be easier to review by looking at the final product at [https://github.com/DominicKramer/nodejs-error-reporting/tree/chore/merge-readme-files](https://github.com/DominicKramer/nodejs-error-reporting/tree/chore/merge-readme-files).

**Comment by alexander-fenster** [comment]
`README.md` is auto-generated by `nodejs-repo-tools`. All these changes will be lost whenever someone runs `npm run generate-scaffolding`. Have you discussed your proposed changes with @jmdobry?

**Comment by jmdobry** [comment]
This is true, your changes here would be overwritten the next time `npm run generate-scaffolding` is executed. I would say we should upstream the more general changes to nodejs-repo-tools. I'm thinking about how to handle the addition of narrative docs.

**Comment by DominicKramer** [comment]
Would it be possible to add a feature to `nodejs-repo-tools` where a "more information" link can be specified in `.cloud-repo-tools.json`.  Then iff this option is specified, the template for the README file would include a link that points to the specified page.

Then I could put the additional information in a page, different from `README.md`, whose contents are not changed by `npm run generate-scaffolding`.

**Comment by jmdobry** [comment]
Yes we can do that.

**Comment by DominicKramer** [comment]
This PR is blocked on nodejs-repo-tools issue [#123](https://github.com/GoogleCloudPlatform/nodejs-repo-tools/issues/123).

**Comment by DominicKramer** [comment]
This PR is too old, which makes it hard to rebase.  Issue #190 has been opened to unblock the features needed to make the change described in this PR, and to add examples to the README file.

**Pull request closed without merging**
