### PR TITLE
docs(samples): modernize samples, sample tests

### PR DESCRIPTION
**Pull request by JustinBeckwith**
This does a few things:
- Updates the sample tests to match modern practices
- Updates the samples to be one per file
- Introduces repo-metadata.yaml to generate the README
- Drops the dependency on repo-tools

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
The docs failures are expected.

**Comment by bcoe** [comment]
@DominicKramer the `.readme-partials.yaml` is customizable, and it looks like @JustinBeckwith has filled it in with quite a bit of content -- what content are you most concerned about overwriting, perhaps we can make sure that's carried over too.

**Comment by JustinBeckwith** [comment]
@DominicKramer does that mean we should add @stephenplusplus as a reviewer?  Trying to figure out if this is "LGTM", or if there are specific things you'd like us to do here :)

**Comment by bcoe** [comment]
@JustinBeckwith my bad, I accidentally `@`d @stephenplusplus; @DominicKramer I meant to ask what the specific concerns were, so that we could potentially flesh them out in the customizable portions of the README.

**Comment by DominicKramer** [comment]
@JustinBeckwith sorry, I should have been more clear.  I don't think this should land yet because it seems to be removing the Unhandled Rejections, Catching and Reporting Application-wide Uncaught Errors, and Long Stack Traces sections from the README (unless I am missing something).

**Comment by JustinBeckwith** [comment]
Got it.  @DominicKramer I went ahead and removed the `README` generation part of this, and just scoped it to the sample infra updates.

**Comment by DominicKramer** [comment]
Sounds good.

**Pull request merged**
