### PR TITLE
chore: Rename src files to `*.ts`

### PR DESCRIPTION
**Pull request by DominicKramer**

### CODE REVIEW

**Comment by DominicKramer** [comment]
PTAL

**Comment by alexander-fenster** [comment]
It does not look like the coverage has actually changed since the previous commit :)

**Comment by DominicKramer** [comment]
@alexander-fenster It looks like the coverage decreased because the system tests exercise the code paths not exercised by the unit tests.  However, the system tests are not run on PRs.

PR #23 contains the current code for the final translation of the repo to Typescript, and it looks like the only drop is from the code tested by only the system tests.

I think the best path forward is to land this PR and the numerous PRs that will be coming that translate the repo to Typescript.  Then after the migration is complete complete, I can work on migrating the small number of system tests to the unit tests by mocking out the network layer used by the tests.  This should bring the coverage back up.

However, I don't want to make these changes to the codebase during an active migration to Typescript.  What do you think?

**Comment by alexander-fenster** [comment]
I'm ok, let me just add an issue to make the unit test reach 100% so that it's not forgotten.

**Pull request merged**
